### ISSUE TITLE
Dont work in MSI GS 75 Stealth, Fedora 35

### ISSUE THREAD

**Issue by JorgeHernandezH** [YoCodingMonster/OpenFreezeCenter#101]
executing the command ./at_startup.sh has no effect, the api does not come up

**Comment by Pixnop** [comment]
same for me but on kubuntu

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
