### ISSUE TITLE
Nothing happens on MSI Alpha 15 B5EEK. Fedora 35.

### ISSUE THREAD

**Issue by midwinters-fall** [YoCodingMonster/OpenFreezeCenter#102]
Executing the command ./at_startup.sh has no effect. The api does not come up.

Fedora 35
Kernel 5.16.18
AMD Ryzen 7 5800H
AMD Radeon RX 6600M

**Comment by Ritul13** [comment]
Did ypu problem has been tesolve till tjos date

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
