### ISSUE TITLE
MSI GF65 Thin, Tails 4.29

### ISSUE THREAD

**Issue by SolRaze** [YoCodingMonster/OpenFreezeCenter#106]
Installed v3.2 with no problems. Tried to configure, nothing worked. Does nothing on selecting any options, Advance opens the window but doesn't modify a thing, EC Mapping closes itself, Monitoring opens a blank terminal. Rebooted, reinstalled, no change. Also app does not run on startup.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
