### ISSUE TITLE
Can't open file 'write_EC.py' on Elementary OS

### ISSUE THREAD

**Issue by ukrenzz** [YoCodingMonster/OpenFreezeCenter#107]
I can't running file **at_startup.sh** using terminal. When running that's file using command, terminal need password. But after put my password, terminal throw a exception :
`python3: can't open file 'write_EC.py': [Errno 2] No such file or directory
`
For now, I using **MSI GF 63 UC10** with Core-i5 10th Gen and Elementary OS 6.1 (Odin).

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
