### ISSUE TITLE
Deb package when?

### ISSUE THREAD

**Issue by robouden** [YoCodingMonster/OpenFreezeCenter#110]
Very happy using a very early version of the app and very happy with it. 
I can not wait for the deb package to arrive to update my setup.

Regards and peace,
Rob Oudendijk

**Comment by marshevms** [comment]
Hi, you can try https://github.com/marshevms/mlfc/releases

**Comment by Carbocode** [comment]
I agree with @marshevms, at this point it's the only one working

**Comment by feelingwalnut** [comment]
not working on debian due to missing /sys/kernel/debug/ec/ec0/io

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
