### ISSUE TITLE
Doesn't seem to work on MSI GE62 VR 6RF Apache Pro (Linux Mint)

### ISSUE THREAD

**Issue by jruiz94** [YoCodingMonster/OpenFreezeCenter#112]
Executing at_startup.sh brings up the interface on the bottom bar, but nothing appears and nothing seems to have any effect

For example every temperature on the following image is 0º, and clicking on Apply doesn't do anything
![imagen](https://user-images.githubusercontent.com/11631730/172496600-11b9667e-5097-4e65-8dee-51bb55c8b887.png)

EC mapping button doesn't work, and clicking on anything else doesn't make fans more silent, either.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
