### ISSUE TITLE
Not working with GS66 Stealth 10SF 10th gen i7

### ISSUE THREAD

**Issue by xyphergrim** [YoCodingMonster/OpenFreezeCenter#115]
The temps aren't showing in the Advanced menu (attached pic) and when I go to Monitor it prompts for password, but when I input password it just simply does a "new line" in the box. Can't ever get past that (attached pic). Therefore, I'm not sure how to tell if anything is working on this model at all? I select different items, but nothing seems to work. Any ideas?
![Monitor-not-working](https://user-images.githubusercontent.com/23463778/175570872-091bce08-58b1-467b-927f-82bd6a627f8d.png)
![Temp-not-working](https://user-images.githubusercontent.com/23463778/175570885-b1888e7e-18de-4ffe-b474-b4c5e80b237f.png)

**Comment by Suirampord** [comment]
for me the same with monitor happens. did you find a solution?

**Comment by Suirampord** [comment]
i found the solution, at least for me. I just installed the zip. you got to install the zip from releases. not just zip the code

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
