### ISSUE TITLE
Kali Linux Support

### ISSUE THREAD

**Issue by GaryH0lt** [YoCodingMonster/OpenFreezeCenter#118]
I tested this application on kali and it is not working.

**Comment by feelingwalnut** [comment]
I'd looked and apparently debian kernel does not have the EC_ whatever module in it. It is supposedly considered a debug feature and not part of the kernel.
Imagine this is a lot of the reason we have so many people saying the program runs but does nothing.

So many distros run the debian kernel and who knows how many other distros don't include the feature.

I'm not certain when this was removed or if it is definitely the issue so many have.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
