### ISSUE TITLE
Ubuntu 22.04 don't work battery threashold

### ISSUE THREAD

**Issue by artt1me** [YoCodingMonster/OpenFreezeCenter#119]
GF63 Thin 11UD 

![Screenshot from 2022-08-02 20-02-15](https://user-images.githubusercontent.com/98020322/182407181-18cc565c-8179-404a-9112-b8b3dfa78ef2.png)

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
