### ISSUE TITLE
on my laptop wont start

### ISSUE THREAD

**Issue by ayamasasaki** [YoCodingMonster/OpenFreezeCenter#120]
hello, I have a problem, my GF75 Thin 9SC wont work this app and for me is important because my laptop don't have a great fan controller on bios and I try to use it on arch Linux and have crash, I send this issues for adding and recommended you to add arch Linux support and support for my laptop if u can.

**Comment by Monsluxe** [comment]
wont start for me neither on a GF63 11SC

**Comment by TheArcaneBrony** [comment]
works fine on arch, though it seems on the gf75 thin 9sc using any option other then cooler boost turns off the cpu fan completely

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
