### ISSUE TITLE
not working on fedora 36

### ISSUE THREAD

**Issue by icebergdd** [YoCodingMonster/OpenFreezeCenter#121]
hey there 
so I ran `at_startup.sh` and nothing happened after scattering through Issues I figured out that I should instal konsole .now it opens a page whenever I run `at_startup.sh` and asks me for sudo password and  when I enter my password, nothing happens .
I also ran `install_deps.sh` but it gives me this error `modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.18.18-200.fc36.x86_64` 
although again I'm not completely sure that the app not running is only bound to these errors .
would be glad to use some help

**Comment by TimmyOl** [comment]
it's only working on debiab or ubuntu based distros, in the scripts it uses apt and gir1.2-appindicator3-0.1 which is debian and ubuntu specific.

I tried changing and installing the possible dependencies so everything is shown in the menu but nothing happens when something is clicked.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
