### ISSUE TITLE
Issues with CPU Profile

### ISSUE THREAD

**Issue by TeaJamFA** [YoCodingMonster/OpenFreezeCenter#126]
After reinstalling distro the CPU profile feature no longer seems to work. It used to but doesn't anymore. I reinstalled the same distro (Mint 21) and even tried EndeavourOS on another partition and it still didn't work. I also couldn't seem to find anything on the config file it correlated to. Can anyone think of any workarounds for this.

**Comment by TeaJamFA** [comment]
This problem seems to be occurring completely at random the CPU profile has worked once in EndeavourOS but never again. Does anyone know what the CPU profile is modifying in the code because I couldn't find it.

I guess I should also mention the specs of my machine I made a new discussion about them: 
https://github.com/YoCodingMonster/OpenFreezeCenter/discussions/130

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
