### ISSUE TITLE
No gui start on GS75 sealth | i7-10750h | rtx 2060

### ISSUE THREAD

**Issue by Pixnop** [YoCodingMonster/OpenFreezeCenter#131]
Hi, 
I tried to remove and put back the conf.txt file but nothing works. I also tried to restart several times but same thing.
video below
https://youtu.be/9nwKvELdArw
Sincerely

**Comment by Pixnop** [comment]
I forgot to say I'm on kubuntu

**Comment by harry-urek** [comment]
I'm having the same issue cmd runs and nothing happens

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
