### ISSUE TITLE
wont launch on Pop_os

### ISSUE THREAD

**Issue by Caspersonn** [YoCodingMonster/OpenFreezeCenter#132]
i have an MSI GF65 9sd and it wont launch.

when i type the ./at_startup.sh command for the first time it creates the conf file but it doesnt start the GUI.

**Comment by constructor-s** [comment]
I encountered the same issue as discussed here: https://github.com/techgaun/nepali-calendar-indicator/issues/5#issuecomment-247910383

After `sudo apt install gir1.2-appindicator3-0.1` it seems to work (though I did try apt install some other stuff before which did not seem to help)

Ubuntu 22.04.1 LTS

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
