### ISSUE TITLE
`root_permissions.sh` is a massive security risk

### ISSUE THREAD

**Issue by pghvlaans** [YoCodingMonster/OpenFreezeCenter#135]
`/etc/sudoers` shouldn't be modified without the user's knowledge in the first place. However, adding `ALL=(root) NOPASSWD:/usr/bin/nohup` to `/etc/sudoers` for the running user is extremely dangerous, as any command prefaced with `sudo nohup` would be run as root without a password prompt.

> TEST AND REPORT ME

If this isn't fixed within the next couple of weeks, I'll report you, all right. To GitHub.

**Comment by TheArcaneBrony** [comment]
reporting is probably overkill, it also seems like their english is quite limited, hence "report me" instead of "report back to me".

**Comment by TheArcaneBrony** [comment]
If you look at my PR, ive gotten rid of the entire root script and I'll probably add a check to the main script to just exit out with "must run as root", as root is required to write to the EC data, instead of this repo's current behavior of self-elevating.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
