### ISSUE TITLE
Is there support for MSI KATANA GF66?

### ISSUE THREAD

**Issue by marioallaa** [YoCodingMonster/OpenFreezeCenter#143]
I have been searching for days on how to interact with the device from ubuntu 22.10, but so far I found nothing that works on KATANA.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
