### ISSUE TITLE
Extract core functionality and expose it as a small lib

### ISSUE THREAD

**Issue by ThibaultLemaire** [YoCodingMonster/OpenFreezeCenter#166]
It would be nice to extract a small library, with minimal dependencies, implementing the core functionality only.

By "core functionality" I mean only reading and writing values to the EC mappings, such that it could be called from an interactive python session.

Why would I need this?

Well let's say I just want to change the battery threshold and forget about it. I'm not interested in any other feature. But I have a device that is not listed as supported (GS65 Stealth 9SD).

Let's also say that I am on NixOS, a weird distribution with an obscure package manager.

And finally let's say that I speak Python.

I currently have to figure out all the dependencies (including non-trivial graphical ones, like `gir-appindicator`), before being able to try an app that I'm not even sure will work.

It seems to me that it would be easier and faster to open an interactive Python session and change the setting I want like so (pseudo code):

```python
import openfreezecenter
openfreezecenter.set_battery_threshold(50)
```

So that's basically what I did, by looking at the code and extracting only what I needed to set the battery threshold. (And the answer is that it does not work, but that's another issue).

And it turns out that this needs absolutely no dependency outside of what is provided by the default python installation (it's just reading and writing to a file). (Well, I still had to `sudo modprobe ec_sys write=1`, but that's not a python dependency anyway.)

---

So that's for my little story, but here are other considerations in favor of extracting that core functionality:
- Making it easier to see what code is actually being run with root priviledges (If I were on e.g. Ubuntu, I would still not be comfortable with a script ripped off github to install stuff on my system without my knowledge)
  - Also makes it cleaner for someone wanting to package your tool in their distribution
- Making it easier to hack. If I'm not just a consumer, but also a potential contributor willing to add support for their hardware, I would like to have easy access to the internals, without going through the whole graphical interface.

**Comment by YoCodingMonster** [comment]
# OpenFreezeCenter-Lite
- Same thing just without much hassle
- https://github.com/YoCodingMonster/OpenFreezeCenter-Lite/tree/v1.0
