### ISSUE TITLE
Some more point, for the SLI Laptop Models (double GPU) like mine MSI GT75 or GT80's Famalies!

### ISSUE THREAD

**Issue by Special-Niewbie** [YoCodingMonster/OpenFreezeCenter#22]
Hello @YoCodingMonster ,

good work man!!!!!

I'm here again just to point you one old point to understand if you will not miss and a new point to list you out ;) :

1) I'm here to reminds you to fix the DPI window problems, on my 4k Monitor testing the app windows are messy because the words will cross to each other, are small and when you will enlarge the Window will not adjust or fix the wording space/ diameter.

2) For some **MSI GT75** as for **GT80's Families**, can mount **Double GPU in SLI** as mine. Nothing Serious, because the FANS are 2 but **BIG** that coll down the CPU and the 2 GPU. But if we want be meticulous to make the app as much perfect as can be possible; on Monitoring temps should be added the GPU0 Temp sensor and GPU1 Temp sensor (or GPU 1 and GPU 2 Temp) as there are 3 Sensor for CPU, GPU0 and GPU1. The Second GPU share the same Head-pipe System from the CPU (so the Second FAN doesn't need the adjustments because it's under the CPU Control (just if you want duplicate the same Voice CPU Fan parallel but under the GPU 2 Infos/ Temps).

3) And another thing if could be possible, on MSI Laptops it's impossible to find a TRAY ICON sensors that works with MSI Motherboards FANS. So, on Linux Systems there are not one software like "Freon" or any others that cannot display and find the fans sensors to display on TRAY ICONS just if I want to see the Fans Icon Tray or display both the Icons + the FANS RPM as this example below:
![Example](https://user-images.githubusercontent.com/64843123/120879776-52fff700-c5f8-11eb-88be-c706218fe7c2.png)

 There is a way to add this possibility in OpenFreezeCenter, to display the Fans RPM with the style as FREON makes? And add into the Software a button to turn on or turn it off on base if you want see or not the RPM Icon on ICON Tray area like below (Sorry for the wording but it's in my language, just to show you the concept):
![Schermata del 2021-06-05 12-22-40](https://user-images.githubusercontent.com/64843123/120879845-ee916780-c5f8-11eb-98ee-fedc79d59cdf.png)

Thank you very much for what you are doing :+1:

**Comment by YoCodingMonster** [comment]
Scaling is what i am working on currently..

This release was kindof quick coz i just wanted to know that do people will love the tray integration or not?

The dual GPU thing will be enabled for selective models. But not in the next release. I need to see the ec_dump for some laptops for that.

ec _dump feature will be included in the next versions and that will help me alot to make custom configurations for each MSI laptop out there.

Information directly in panel will be taken after ec_dump system is fuley functional!!!!!

**Comment by Special-Niewbie** [comment]
All clear, thanks a lot, don't take me bad just I'm here to reminds you in case you have to follow many things, because I see that you have to do a lot ;).

What do you think, for the TRAY Icon, in case some one don't like (personally I love to see), you could consider to add the function to deactivate the ICON TRAY in the same as I show you on the top, to add one button bar....
Have good work on that :+1:
