### ISSUE TITLE
Doesn't work on MSI GS65 - Kubuntu 20.04

### ISSUE THREAD

**Issue by techarek** [YoCodingMonster/OpenFreezeCenter#24]
I am able to run on_startup.sh, and the application shows up in my taskbar. However, changing the settings does nothing.

**Comment by YoCodingMonster** [comment]
you need to reboot once after first install

**Comment by YoCodingMonster** [comment]
@techarek is it working now?

**Comment by techarek** [comment]
It does not work after a reboot (I tried it before and also again now)

**Comment by YoCodingMonster** [comment]
Try this command in terminal `sudo apt install nautilus -y`

and then runt he script?
@techarek

**Comment by techarek** [comment]
nautilus was already installed from the last time (since the dependency script installs it), so that also didn't work. One thing I noticed is that the files aren't executable so i chmod +x the scripts and python files - maybe that has something to do with it (maybe I missed permissions for another file).

**Comment by techarek** [comment]
Also possibly related, monitoring gets stuck at asking for password even after I put it in.

**Comment by YoCodingMonster** [comment]
@techarek 
nautilus-admin was the package for giving nautilus root access.
you must actually have the nautilus file explorer in order to do that..

not having nautilus will not install the modprobe files in place and the app will not work.
so run command
`sudo apt install nautilus -y`
then Delete the `conf.txt` file in the directory
reboot the system and then open terminal in directory and run `at_startup.sh`

if after that the thing do'sent work, then wait till the next release. i will do some modifications for it!

**Comment by techarek** [comment]
Yeah sorry I forgot to mention that I did run the command to install nautilus (though it turns out I already had it installed). It's my bad I misremembered which package was in the dependency, but it still doesn't work. Thanks for the dedication though and I will wait for the next release.

**Comment by YoCodingMonster** [comment]
Do you have by any chance some instance of terminal open while you were trying to change settings through the app.
any other terminal windows not opened by this app?

**Comment by techarek** [comment]
Yes, I keep the original terminal that I ran at_startup with open.

**Comment by YoCodingMonster** [comment]
Hmm, i need to look into it further, maybe by installing kbuntu 20.04 and testing it myself. but thanks to bring this issue into light.

will definitely patch this in my next release!!

**Comment by cbutakoff** [comment]
If it helps, in linux mint 20.1 there is no file /sys/kernel/debug/ec/ec0/io:
```
Traceback (most recent call last):
  File "write_EC.py", line 74, in <module>
    write_EC(vr_new, battery_threshold)
  File "write_EC.py", line 16, in write_EC
    with open(EC_IO_FILE,'w+b') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
```

**Comment by YoCodingMonster** [comment]
> If it helps, in linux mint 20.1 there is no file /sys/kernel/debug/ec/ec0/io:
> 
> ```
> Traceback (most recent call last):
>   File "write_EC.py", line 74, in <module>
>     write_EC(vr_new, battery_threshold)
>   File "write_EC.py", line 16, in write_EC
>     with open(EC_IO_FILE,'w+b') as file:
> FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
> ```

This tells me that the system EC write enabler files didnt got installed at all!.
Thanks that narrowed it down for me to work on!!

**Comment by techarek** [comment]
> If it helps, in linux mint 20.1 there is no file /sys/kernel/debug/ec/ec0/io:
> 
> ```
> Traceback (most recent call last):
>   File "write_EC.py", line 74, in <module>
>     write_EC(vr_new, battery_threshold)
>   File "write_EC.py", line 16, in write_EC
>     with open(EC_IO_FILE,'w+b') as file:
> FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
> ```

How did you get this output? I removed the `> /dev/null` for the python call and I did not get any explicit error. I think it fails for me completely silently.

**Comment by techarek** [comment]
@YoCodingMonster `sudo modprobe ec_sys write_support=1` fixes the problem for me - can add this to at_startup.

**Comment by YoCodingMonster** [comment]
> @YoCodingMonster `sudo modprobe ec_sys write_support=1` fixes the problem for me - can add this to at_startup.

Thanks for the help!!!!!

**Comment by cbutakoff** [comment]
Yes, the modprobe totally works. Thanks for the code! Super useful!
