### ISSUE TITLE
Various installer problems

### ISSUE THREAD

**Issue by Haptein** [YoCodingMonster/OpenFreezeCenter#25]
First of all, thanks for working on this tool! 🚀

I'll just note here some observations on the installation files:
- Using python3 as is on at_startup.sh won't use the system's python installation if the user uses conda or something like that. Perhaps using /usr/bin/python3 is a better way, but I'm not really sure what's the standard way of doing it.
- Using nohup might be a bad idea, if something goes wrong it goes wrong silently. There's no way for the user to tell if the installation went without problems, or at least if it did encounter any.
- install_deps.sh will fail on any distro that doesn't use apt as it's package manager.

**Comment by Haptein** [comment]
Actually looks like PR #19, deals with these three things.

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!
