### ISSUE TITLE
installation script fails

### ISSUE THREAD

**Issue by Meatballs4Breakfast** [YoCodingMonster/OpenFreezeCenter#26]
Hi,, for me at_startup.sh fails, and if i manually run ./install_deps.sh it tells me this:

Package gir1.2-appindicator3-0.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gir1.2-appindicator3-0.1' has no installation candidate
install: 'etc/modprobe.d/ec_sys.conf' and '/home/user/Scrivania/OpenFreezeCenter-main/etc/modprobe.d/ec_sys.conf' are the same file
install: 'etc/modules-load.d/ec_sys.conf' and '/home/user/Scrivania/OpenFreezeCenter-main/etc/modules-load.d/ec_sys.conf' are the same file

And python3 indicator.py tells me this:

└─$ python3 indicator.py                                                                                       1 ⨯
/home/user/Scrivania/OpenFreezeCenter-main/indicator.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository  import Gtk as gtk
Traceback (most recent call last):
  File "/home/user/Scrivania/OpenFreezeCenter-main/indicator.py", line 9, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 131, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name AppIndicator3, introspection typelib not found

Not sure if this is useful, i'm using a borrowed GT72VR 7RD, and i have to run kali linux for a university project, i was trying to install your app because a fan behaves weirdly, but it fails.

**Comment by YoCodingMonster** [comment]
For the Indicator.py error, replace the starting imports with

```
import signal
import os
import subprocess
import webbrowser
import fileinput
import gi.repository
from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
import gi.repository
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
```

**Comment by YoCodingMonster** [comment]
for kali users i will be enabling install supports of libraries in next release!!

**Comment by Meatballs4Breakfast** [comment]
Wow thank you!
I wish i could help, but i'm ultra noob at coding and i don't know anything (yet).
Thanks for working on this.

**Comment by Meatballs4Breakfast** [comment]
Hi again, sorry for the late response.

So i've replaced the imports, however it gives the same error, so after reading the error message, that states that gi.require_version('Gtk', '3.0') and
gi.require_version('AppIndicator3', '0.1') goes before imports i changed your code from this:

#! /usr/bin/python3

import signal
import os
import subprocess
import webbrowser
import fileinput
import gi.repository
from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
import gi.repository
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')

To this:

#! /usr/bin/python3

gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
import signal
import os
import subprocess
import webbrowser
import fileinput
import gi.repository
from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
import gi.repository

And now it gives me this:

Traceback (most recent call last):
  File "/home/user/Desktop/OpenFreezeCenter-main/indicator.py", line 3, in <module>
    gi.require_version('Gtk', '3.0')
NameError: name 'gi' is not defined

Sorry again, i'm open with whatever you may need, just hmu.

**Comment by YoCodingMonster** [comment]
Sorry my bad, really sorry
Try replacing this with the imports

```
import signal
import os
import subprocess
import webbrowser
import fileinput
import gi.repository
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
from gi.repository  import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
```

**Comment by Meatballs4Breakfast** [comment]
Done, however:

Traceback (most recent call last):
  File "/home/user/Desktop/OpenFreezeCenter-main/indicator.py", line 10, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

Wish i could help you more.

**Comment by YoCodingMonster** [comment]
Open terminal and type

`sudo apt-get install gir1.2-appindicator3-0.1`
And
`sudo apt install libappindicator3-dev`

And then run it

**Comment by Meatballs4Breakfast** [comment]
I had already tried to do that in my feeble attempt at fixing this, however both return error, specifically:

Package gir1.2-appindicator3-0.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gir1.2-appindicator3-0.1' has no installation candidate

and

└─# apt-get install libappindicator3-dev                           100 ⨯ 1 ⚙
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libappindicator3-dev

**Comment by YoCodingMonster** [comment]
Try this

`sudo apt install python3-gi`

**Comment by Meatballs4Breakfast** [comment]
Already newest version, also tried, sorry.

**Comment by YoCodingMonster** [comment]
> Already newest version, also tried, sorry.
> 
> Also no pressure, i realize i'm no help at all, so i don't want to bother.

thats fine. i just dont have a team or multiple MSI laptops to test this software in....
I use ubuntu and i know kali and ubuntu have some differences in their dependencies versions and how they work....
so in a couple of release this issue will be fixed.. i really need people shifting to linux system and MSI laptops have a big chunk of Linux users out there....
Thats the motivation behind me making this application!!

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!

**Comment by terryalava** [comment]
i managed to get the UI (the problem that Meat was having) by adding "ayatana" to appindicators as they explain in this post 'libappindicator3-1 was replace by libayatana-appindicator3-1 ' 
https://github.com/GetPublii/Publii/issues/1026

i did this to indicator.py and install_deps.sh

however no options are working after the clic in  any options
i found that maybe the main reason is because is trying to read files that doesn't exist in kali linux, like this:
EC_IO_FILE = '/sys/kernel/debug/ec/ec0/io' in [monitor.py](url)
or they might have a different name and location

i found that lm-sensors package gives you the core temps as well as others from the laptop, maybe if you point your code to read info from that, it might be the next step, i don't do it because i don't fully understand your code and how it works

looking forward to increase the speed of my fans in kali linux 2022, with Cooler Booster

(i have an msi crosshair 15 11gen rtx 3060 laptop)
[3.1.zip](https://github.com/YoCodingMonster/OpenFreezeCenter/files/8357484/3.1.zip)
[main.zip](https://github.com/YoCodingMonster/OpenFreezeCenter/files/8357485/main.zip)
