### ISSUE TITLE
Icon issue in tray on Mate Desktop 1.24

### ISSUE THREAD

**Issue by volnes** [YoCodingMonster/OpenFreezeCenter#27]
icon of app is oversized on mate desktop 1.24
![gigant icon](https://user-images.githubusercontent.com/5400851/121029233-1b887a80-c7b1-11eb-98d3-8bcef2baba38.png)

**Comment by Special-Niewbie** [comment]
The Penguin it's watching you.......

**Comment by YoCodingMonster** [comment]
> icon of app is oversized on mate desktop 1.24
> ![gigant icon](https://user-images.githubusercontent.com/5400851/121029233-1b887a80-c7b1-11eb-98d3-8bcef2baba38.png)

Will get fixed in the next release

**Comment by volnes** [comment]
@YoCodingMonster close this issue, fixed!
