### ISSUE TITLE
MSI GS63VR - Some little bugs but I managed to make it work

### ISSUE THREAD

**Issue by IvanoiuAlexandruPaul** [YoCodingMonster/OpenFreezeCenter#30]
Hello everyone. 

My name is Alex and I own an MSI GS63VR

So maybe you wonder how to install the program right? since for now if you try nothing happens.

Well, to install it you have to do the following steps:

1. sudo apt-get install python3-tk -y
2. Open the folder :  /etc/etc/modules-load.d/ and check for the file ec_sys.conf. If you can no find it copy it from the folder etc on Github 
3. Open the folder: /etc/modprobe.d/ and check for the file ec_sys.conf. If you can no find it copy it from the folder etc on Github
4. Open the folder with all the files that you downloaded from GitHub and change the permission of ALL the files in the folder from read-only to read-write and check the execution box that stays below the read permission for OTHER users.
5. Once you did all that you can open the terminal inside the folder and execute the ./at_startup.sh and it will work for sure if you did all the steps above one after the other.

Notice that for NOW every time you restart your PC you will have to re-execute the line code: ./at_startup.sh

Big problem is that once you execute that some install commands won't work anymore because the process is looking the root process let's say and you can not install the programs so before starting the dragon center make sure you install everything that you want first. 

Hope I helped someone.

All the work has been done by the owner of this GitHub repository and I managed to make it work just with the help of @Special-Niewbie here on GitHub so special Thanks to them.

**Comment by HiPatil** [comment]
Still not working! Followed step by step

**Comment by YoCodingMonster** [comment]
> Still not working! Followed step by step
> 

Wait for sometime...we are working on a debian install package...
Once it is complete...we will let you know

**Comment by HiPatil** [comment]
I think I found a solution!
When I run `python3 indicator.py` it gives error `No module name gi'
Installing that worked for me.

P.S. If your are using conda, get out of base environment too!

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!
