### ISSUE TITLE
Dosen't work with the MSI G75 Leopard 10SDR

### ISSUE THREAD

**Issue by Vexzyl** [YoCodingMonster/OpenFreezeCenter#32]
I can run it, but there's no change when I change the fan speeds or enable the cooler booster.

**Comment by YoCodingMonster** [comment]
> I can run it, but there's no change when I change the fan speeds or enable the cooler booster.

Did you follow all the instructions?

**Comment by Vexzyl** [comment]
i think i fixed it by reinstalling the OpenFreezeCenter

**Comment by Vexzyl** [comment]
Yeah, it works now, after reinstalling the NVIDIA driver and the OpenFreezeCenter.

**Comment by Special-Niewbie** [comment]
With all 75 series the software it's working ;). 

Yesterday I started to fork the software, I fixed the installation problems and then @YoCodingMonster  please man without bother you, but I would like to keep in contact to you in some way to share the ideas and results to take out the limit of the sudo password (I was thinking to create a .deb package?!). I'm testIng on Debian/Deepin for now....

**Comment by YoCodingMonster** [comment]
> With all 75 series the software it's working ;). 
> 
> Yesterday I started to fork the software, I fixed the installation problems and then @YoCodingMonster  please man without bother you, but I would like to keep in contact to you in some way to share the ideas and results to take out the limit of the sudo password (I was thinking to create a .deb package?!). I'm testIng on Debian/Deepin for now....

Great bro..
I do not have experience building .deb packages....never have build them actually...

That would be a nice help

**Comment by Special-Niewbie** [comment]
> > With all 75 series the software it's working ;). 
> > 
> > Yesterday I started to fork the software, I fixed the installation problems and then @YoCodingMonster  please man without bother you, but I would like to keep in contact to you in some way to share the ideas and results to take out the limit of the sudo password (I was thinking to create a .deb package?!). I'm testIng on Debian/Deepin for now....
> 
> Great bro..
> I do not have experience building .deb packages....never have build them actually...
> 
> That would be a nice help

Me too 😅....in this case I will study on it to achieve it. When I will need some help about some Python functions (like to fix the DPI) I will contact you back 😉

**Comment by YoCodingMonster** [comment]
> > > With all 75 series the software it's working ;). 
> > > 
> > > Yesterday I started to fork the software, I fixed the installation problems and then @YoCodingMonster  please man without bother you, but I would like to keep in contact to you in some way to share the ideas and results to take out the limit of the sudo password (I was thinking to create a .deb package?!). I'm testIng on Debian/Deepin for now....
> > 
> > Great bro..
> > I do not have experience building .deb packages....never have build them actually...
> > 
> > That would be a nice help
> 
> Me too 😅....in this case I will study on it to achieve it. When I will need some help about some Python functions (like to fix the DPI) I will contact you back 😉

Sure!!
