### ISSUE TITLE
Fedora Support

### ISSUE THREAD

**Issue by kapiljhajhria** [YoCodingMonster/OpenFreezeCenter#36]
Hi, I am a fedora user and I have already tried isw but it doesn't work due to lack of ec_sys module. 
I tried your app as well but it doesn't work.
My laptop is MSI GF63 9SC thin NVIDIA 1650 Card
I am ready to test it for you on fedora. How do I reach you? Telegram? Discord?

**Comment by YoCodingMonster** [comment]
You can join me on reddit chat..that will be fine!!

**Comment by tanishq-mishra** [comment]
Hey! could you get it to work on Fedora?

**Comment by YoCodingMonster** [comment]
We are working on making it work on every distro
