### ISSUE TITLE
Arch Support 

### ISSUE THREAD

**Issue by AlfonsoJPH** [YoCodingMonster/OpenFreezeCenter#37]
I have modified the files to make it works partially with Arch linux, but it still has some things to change for make it works properly.

First of all, before executing it for the first time you must enter the Indicator.py file and change the TERMINAL variable for the terminal that you have installed, by default I have left it in alacritty, which is the one I use.
Also, to start the program it is better to use sudo python3 ./at_startup.sh because I have not yet managed to make the root_permissions.sh script work(Otherwise each action you execute you will have to write the password).

Finally, the only function that does not work for me is the monitor, it only gives the first temperature reading, but the fans stay at 0 and the temperature is not updated.

I left the tar with the files adapted for Arch.
[Open-Freezer-Center-Arch.tar.gz](https://github.com/YoCodingMonster/OpenFreezeCenter/files/6826532/Open-Freezer-Center-Arch.tar.gz)

Hope I helped someone.

**Comment by YoCodingMonster** [comment]
I will have a look into that and made the necessary changes to it!

**Comment by dgva** [comment]
I am changing from Kubuntu to Manjaro, I will test and report later! Thank you

**Comment by Abbas1110** [comment]
appindicator in install_deps.sh can not be found. But it is a gnome-shell-extension. Nevertheless it does not work with me. I work on arch. I have MSI Stealth 15M.

**Comment by khoihuynh2409** [comment]
> 

it's work, great!!! thanks!!!

**Comment by khoihuynh2409** [comment]
it's work, thanks!!!!

**Comment by Bincode-0** [comment]
I have managed to get this working on an MSI Laptop GL65 Leopard with i3wm and polybar, thanks very much. 
If it helps the monitoring and ec_mapings options didn't work until i installed tk from the aur. I figured it out by executing the ec_dump.py script manuallly searching for errors.

Again ty
