### ISSUE TITLE
OFC can't control fans when conf.txt exists

### ISSUE THREAD

**Issue by manchitro** [YoCodingMonster/OpenFreezeCenter#39]
When I run at_startup.sh for the first time, it asks for my password 3 times. From what I understand from the code, once for root_permissions.sh, another for install_deps.sh.
(No idea about the third time tho). Then conf.txt is created and the appindicator runs and works flawlessly (since I've given everything sudo access by typing in my password, it can control the fan and whatnot)

Then let's say I reboot, conf.txt is already there. The logic in indicator.py (as far as I understand) says that if conf.txt exists, don't execute root_permissions and install_deps and directly create appindicator. But this time the program cannot control the fans. I guess because this time it doesn't have sudo access since it didn't ask for my password. To run OFC successfully again, I have to delete conf.txt so that it can acquire sudo access in indicator.py. And then I have to type my password 3 consecutive times which is tiresome.

Maybe I'm missing something? I've shifted to linux a few days ago and has always been a Windows user. Is it how OFC supposed to work?

Running Pop!_OS 21.04

**Comment by YoCodingMonster** [comment]
We will look into the matter....

OFC is not suppose to work like that...
We will fix it in our next release..

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!
