### ISSUE TITLE
No fan control on MSI GF63 9RCX Model

### ISSUE THREAD

**Issue by sanjaybhandarii** [YoCodingMonster/OpenFreezeCenter#41]

**Comment by YoCodingMonster** [comment]
Can you describe the error or problem you faced

**Comment by shawn00-tech** [comment]
> Can you describe the error or problem you faced
I ran cooler boost mode but nothing happened. I think none of the profiles given doesnot work.

**Comment by tridot64** [comment]
try disabling secure boot that worked for me

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!

**Comment by YoCodingMonster** [comment]
new release
