### ISSUE TITLE
Turbo Boost ON/OFF switch

### ISSUE THREAD

**Issue by R1D3R175** [YoCodingMonster/OpenFreezeCenter#45]
A feature for enabling or disabling Turbo Boost would be awesome.

**Comment by YoCodingMonster** [comment]
You are talking about the GU overclock or just the fans...
for just the fans Cooler Boost does the same

**Comment by R1D3R175** [comment]
I'm talking about the GUI. As you know, MSI puts the base frequency at some standard ~2.8GHz and then pumps it up to 5GHz with Turbo Boost; this makes the laptop heat up in no time for just no reason.

I thought that being able to disabling it would be very cool from the App Indicator since, atm, I've to use some .sh scripts...

Also, another idea could be: modifying the Turbo Ratio Limit through GUI (like Advanced for fans). 

P.S. Could it be possible to undervolt?

**Comment by YoCodingMonster** [comment]
i will get to that later, but will try by the end of this year
