### ISSUE TITLE
GPU Temp not found on MSI GF63 Thin 10SC-055IT

### ISSUE THREAD

**Issue by R1D3R175** [YoCodingMonster/OpenFreezeCenter#46]

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!

and also check if you have disabled the GPU by another software

**Comment by R1D3R175** [comment]
in this week I tried out different things, and I found out that the main problem was that GPU was not being "used" by Ubuntu. I had the option "Nvidia On-Demand" in X Server but quickly realized that it won't work with some other programs, so I switched out to Performance Mode and now it gets detected by the program flawlessly.

In my opinion, the main reason for which the GPU wasn't recognized it's that it wasn't just used, but when you used Performance Mode you actually use it for everything and works (?)

**Comment by YoCodingMonster** [comment]
Yep.. I didn't knew that your laptop was on ..on demand... Mode XD..
I thought this whole time that heat is missing in the code...

**Comment by R1D3R175** [comment]
I'm so sorry for that! Next time I'll provide more information!
