### ISSUE TITLE
bash: ./at_startup.sh: Permission denied

### ISSUE THREAD

**Issue by mits0s1994** [YoCodingMonster/OpenFreezeCenter#49]
Hello there, im kinda new to this Linux thing so im newbie! i have an MSI laptop GF63 thin 9SC with Pop os 21.04 and im getting that permission error after trying to do the ./at_startup.sh in the proper unzipped folder. Can anyone help me with that? Thanks in advance!

**Comment by YoCodingMonster** [comment]
Try this command first

chmod +x at_startup.sh

Then run this

./at_startup.sh

**Comment by mits0s1994** [comment]
Ok, that worked. It created the conf.txt file BUT, when i run the command again to open the GUI, it does nothing. Any ideas?

**Comment by YoCodingMonster** [comment]
Did you reboot?..

**Comment by mits0s1994** [comment]
I did reboot indeed. Nothing seems to be happening when i input the command. Just to be sure, i'm doing cd/Downloads/OpenFreezeCenter-main and then i type in ./at_startup.sh . If i'm doing that correctly, then no, nothing seems to be happening.

**Comment by YoCodingMonster** [comment]
Just wait for the next release then which will be on Sunday...I will fix that error!

**Comment by YoCodingMonster** [comment]
try the latest release instead, if it dosent work then report back

**Comment by mits0s1994** [comment]
Alright! Thanks a lot for the responses! I will let you know at Sunday!

**Comment by alnork** [comment]
Hi,

Excellent initiative. I'm close to remove DualBoot and disgusting Windows and would like to have something like the MSI Dragon Center in my Mint. The same thing happens to me as @mits0s1994. I have an MSI GL73 9RCX.

**Comment by YoCodingMonster** [comment]
new release

**Comment by MSrIan** [comment]
Nvm, i installed previous version an it works perfectly on MSI Bravo 15 ADDR4(model with 144Hz display not with 120Hz). But one more  question, when i restart the laptop the program isn't there, i must to type again ./at_startup.sh.

**Comment by YoCodingMonster** [comment]
I will be looking into it and release next version on sunday
