### ISSUE TITLE
How to enable startup?

### ISSUE THREAD

**Issue by Mahraway** [YoCodingMonster/OpenFreezeCenter#51]
I added to the startup list in Startup Application. But when the system is turned on, the program does not start. 

P.S. I have set the required execution rights

**Comment by YoCodingMonster** [comment]
That will be added in another update

**Comment by alkaaf** [comment]
> I added to the startup list in Startup Application. But when the system is turned on, the program does not start.
> 
> P.S. I have set the required execution rights

instead of putting 
`./at_startup`
in the Startup Application, i tried
`/usr/bin/python3 <openfreezecenter_dir>/indicator.py`
did the trick
