### ISSUE TITLE
I installed the program but nothing happens - MSI GS65, Debian 11

### ISSUE THREAD

**Issue by Qyra123** [YoCodingMonster/OpenFreezeCenter#52]
I've installed it simply with "./at_startup.sh", installer opened it installed  and it closed, no errors.
I did ./at_startup.sh again, but nothing happened.
The GUI or the program doesn't show up, there is nothing on the bar either.
What should I do?

**Comment by Mahraway** [comment]
Надо дать права на исполнения этому файлу. Попробуй: sudo chmod 777 -R OpenFeezeCenter

**Comment by YaduAhuja** [comment]
It must have been because of dependencies not installed correctly. Execute the commands one by one from install_deps.sh. 
Then try again.

**Comment by Qyra123** [comment]
I've succesfully installed all dependencies one by one from install _deps.sh, except for one;
sudo modprobe ec_sys write_support=1
I get this output:
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.10.0-8-amd64

I've done a research myself and I think it just says module ec_sys is missing from the kernel,
but I couldn't make it work.
My Secure boot is disabled and I've rebooted a couple times, BTW.

I've run at_startup.sh again, but still nothing seems to happen.

Sorry for the hassle and thank you in advance.

**Comment by YoCodingMonster** [comment]
Have you installed both the files from the ```etc``` folder too..without that the software dosent work?

**Comment by kshitij-murabatte** [comment]
Hi, how do I install the two files in **etc** folder. I am using GF65 Thin.

**Comment by YoCodingMonster** [comment]
Use the ```install``` command in the ```install_depa.sh``` file

**Comment by kshitij-murabatte** [comment]
Thanks a lot man!!!!

**Comment by kshitij-murabatte** [comment]
Hi again, I was wondering how to get **Battery Charge Threshold** to work.
