### ISSUE TITLE
Battery Threshold not working  

### ISSUE THREAD

**Issue by ThomasArtin** [YoCodingMonster/OpenFreezeCenter#58]
Setting the battery threshold does not do anything and the battery continues to charge.
Laptop : MSI GF65-thin 9SEXR
Linux Distro : POP-OS 20.04 LTS

**Comment by YoCodingMonster** [comment]
battery threshold doesn't work for now, but working on this feature at present

**Comment by ThomasArtin** [comment]
Great ! Thanks for this amazing tool dude you saved us
