### ISSUE TITLE
Prestige-15-A11SCS issue

### ISSUE THREAD

**Issue by feduss** [YoCodingMonster/OpenFreezeCenter#60]
Hi!
When i execute ./at_startup.sh nothing happened :/...but the conf.txt is created.
If can help, my cpu is a i7-1185g7 and i have ubuntu 21.

**Comment by volnes** [comment]
try just run indicator.py
python3 /home/<path_to_openfreeze_center>/indicator.py
and download not openfreezecenter not 3.2, take it from there
https://github.com/YoCodingMonster/OpenFreezeCenter/archive/refs/heads/main.zip

**Comment by volnes** [comment]
Try install
sudo apt-get install gir1.2-appindicator3-0.1

ср, 6 окт. 2021 г., 23:41 Federico Saccà ***@***.***>:

**Comment by YoCodingMonster** [comment]
Working on it!!

**Comment by feduss** [comment]
Running sudo apt-get install python3-tk  and sudo ./install_deps.sh make this tool working! Thanks! :)! Next step is to don't ask sudo for every change :D
