### ISSUE TITLE
GF63 Thin 9RCX not working

### ISSUE THREAD

**Issue by mak163** [YoCodingMonster/OpenFreezeCenter#62]
OS: Arch Linux
DE: KDE Plasma 5.22
When i execute ./at_startup.sh nothing happened, but the conf.txt is created.

**Comment by mak163** [comment]
After several attempts to start, the indicator appeared in the system tray, but the program has no positive effect on fan control. The cooler booster does not work.

**Comment by mak163** [comment]
There is still no new version. Is there any hope that someday there will be? Maybe something can help?

**Comment by mak163** [comment]
> Try previous version 3.1

Unfortunately it doesn't work either.

**Comment by RushanKhan1** [comment]
I have *GF63 8RD* and I am literally facing the same issue. Icon appeared on the system tray, but none of the options (other than quit) seems to work.
