### ISSUE TITLE
MSI Delta 15 Fedora 34 not working

### ISSUE THREAD

**Issue by b310v3** [YoCodingMonster/OpenFreezeCenter#65]
Report for MSI delta 15, after running at_startup.sh nothing happen, the spec is AMD Ryzen 5900HX and Radeon 6700M.

**Comment by luke512** [comment]
Also not working for me on arch. I've tried other fan control software but they only detect the gpu fan and changing the curve does nothing.

**Comment by b310v3** [comment]
Seem like Gnome had disable system tray. You can try using this to get it working, I haven't try this yet.
https://extensions.gnome.org/extension/615/appindicator-support/
