### ISSUE TITLE
MSI GT62VR 7RE report

### ISSUE THREAD

**Issue by rsluchevskiy** [YoCodingMonster/OpenFreezeCenter#70]
First of all, thank for your work! Setup on 62VR works, cpu and gpu temperature in monitoring seems to be correct, fan speed adjusts accordingly to settings. The only thing i noticed is that current fan speed for both cpu and gpu in monitoring is always zero rpm, max in % seems to be correct, min in % is also zero.

Ubuntu 20.04
i7 7th gen
gtx 1070

**Comment by YoCodingMonster** [comment]
will look into this problem
