### ISSUE TITLE
MSI GS66 WORK

### ISSUE THREAD

**Issue by mathys-l** [YoCodingMonster/OpenFreezeCenter#71]
On my MSI GS66 thah work, but the explain how install can upgrade, missing chmod +x <files> and start by run install dependencies.

**Comment by JosefNatanael** [comment]
It also works on my MSI GS66 (10gen 2060)

**Comment by JosefNatanael** [comment]
The battery threshold feature doesn't seem to work on my GS66 (10gen, 2060) though. It keeps charging to 100. But the rest works.
