### ISSUE TITLE
MSI Stealth 15M

### ISSUE THREAD

**Issue by Abbas1110** [YoCodingMonster/OpenFreezeCenter#74]
Hallo, 

I wanna start by saying that you are doing an absolutely amzing job. I was about to quit linux because of msi center. It is a very necessary tool. However your program does not work with my stealth. Could you please fix this issue.
I have intel core i7 1185G7 with nvidia gtx 1660ti.
"sudo: ./at_startup.sh: command not found" this is what I get when I try to install it.

Thank you in advance.

**Comment by volnes** [comment]
just run ./at_startup.sh without sudo

**Comment by Abbas1110** [comment]
I thought sudo is just saying that im an administrator and It does not affect the command in itself. However I changed the permissions of the file with chmod +x at_startup.sh because it was asking for administrator permission. Sadly it didnt work either. 
But this time I did not show any error on the terminal. I just dont see anything on the top bar where it should be.
Can you please guide me to solve this?
Thank you

**Comment by Abbas1110** [comment]
I had to install install_deps.sh first and now it worked. Perfect work man thank you very much
