### ISSUE TITLE
msi gf75 10scxr not working 

### ISSUE THREAD

**Issue by kimito1R** [YoCodingMonster/OpenFreezeCenter#75]
i'm very new into linux i tried installed the software but it didn't have any effect i hope there's a solution i use garuda

thank you very much in advance and sorry for the inconvenience

**Comment by sudo-Tiz** [comment]
Same issue 
First, i had to install gir1.2-appindicator3-0.1 wich is not installed in ubuntu 20.04 .
Then nothing seams to work. I can open the monitoring gui but the values are wrong.

MSI GF75 10scxr 
OS: Ubuntu 20.04.3 LTS x86_64 
Host: GF75 Thin 10SCXR REV:1.0 
Kernel: 5.11.0-43-generic 
Shell: bash 5.0.17

**Comment by sudo-Tiz** [comment]
I am using msi gf75 10scxr and it work well.
first diable secure boot in your bios, then you have to run
sudo  ./install_deps.sh
sudo ./root_permissions.sh
and then  ./at_startup.sh

then maybe restart
