### ISSUE TITLE
openSUSE support, please...

### ISSUE THREAD

**Issue by lemmy04** [YoCodingMonster/OpenFreezeCenter#78]
I'm trying to run this on openSUSE, no luck so far - all I get is lots of errors because openSUSE doesn't know a "x-terminal-emulator" command.

I tried creating a softlink in ~/bin (which is in my $PATH) to /usr/bin/xterm which seems to sort of fix it, but whenever I pick a menu option allI get is a windows that disappears immediately.

**Comment by volnes** [comment]
look into install_deps.sh and install dependecies

**Comment by lemmy04** [comment]
already did that. like I already said: openSUSE does not have a "x-terminal-emulator" command.

**Comment by volnes** [comment]
it have called gnome-terminal
`zypper in gnome-terminal`

**Comment by lemmy04** [comment]
```
mathias@mio:~> sudo zypper in gnome-terminal
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 2 NEW packages are going to be installed:
  gnome-terminal gnome-terminal-lang

2 new packages to install.
Overall download size: 1.7 MiB. Already cached: 0 B. After the operation, additional 9.5 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package gnome-terminal-3.42.1-1.1.x86_64                                                     (1/2), 684.1 KiB (  3.2 MiB unpacked)
Retrieving: gnome-terminal-3.42.1-1.1.x86_64.rpm ......................................................................................[done]
Retrieving package gnome-terminal-lang-3.42.1-1.1.noarch                                               (2/2), 1021.5 KiB (  6.3 MiB unpacked)
Retrieving: gnome-terminal-lang-3.42.1-1.1.noarch.rpm .................................................................................[done]

Checking for file conflicts: ..........................................................................................................[done]
(1/2) Installing: gnome-terminal-3.42.1-1.1.x86_64 ....................................................................................[done]
(2/2) Installing: gnome-terminal-lang-3.42.1-1.1.noarch ...............................................................................[done]
mathias@mio:~> x-terminal-emulator
Wenn 'x-terminal-emulator' kein Tippfehler ist, können Sie command-not-found benutzen, um das Paket zu finden, das den Befehl enthält, z. B.:
    cnf x-terminal-emulator
mathias@mio:~> 
```
**openSUSE does not have a "x-terminal-emulator" command.**

**Comment by volnes** [comment]
well then it's debian based thing. Perl script.

`#!/usr/bin/perl -w

my $login=0;

while ($opt = shift(@ARGV))
{
    if ($opt eq '-display')
    {
        $ENV{'DISPLAY'} = shift(@ARGV);
    }
    elsif ($opt eq '-name')
    {
        $arg = shift(@ARGV);
        push(@args, "--window-with-profile=$arg");
    }
    elsif ($opt eq '-n')
    {
        # Accept but ignore
        print STDERR "$0: to set an icon, please use -name <profile> and set a profile icon\n"
    }
    elsif ($opt eq '-T' || $opt eq '-title')
    {
        push(@args, '-t', shift(@ARGV));
    }
    elsif ($opt eq '-ls')
    {
        $login = 1;
    }
    elsif ($opt eq '+ls')
    {
        $login = 0;
    }
    elsif ($opt eq '-geometry')
    {
        $arg = shift(@ARGV);
        push(@args, "--geometry=$arg");
    }
    elsif ($opt eq '-fn')
    {
        $arg = shift(@ARGV);
        push(@args, "--font=$arg");
    }
    elsif ($opt eq '-fg')
    {
        $arg = shift(@ARGV);
        push(@args, "--foreground=$arg");
    }
    elsif ($opt eq '-bg')
    {
        $arg = shift(@ARGV);
        push(@args, "--background=$arg");
    }
    elsif ($opt eq '-tn')
    {
       $arg = shift(@ARGV);
       push(@args, "--termname=$arg");
    }
    elsif ($opt eq '-e')
    {
        $arg = shift(@ARGV);
        if (@ARGV)
        {
            push(@args, '-x', $arg, @ARGV);
            last;
        }
        else
        {
            push(@args, '-e', $arg);
        }
        last;
    }
    elsif ($opt eq '-h' || $opt eq '--help')
    {
        push(@args, '--help');
    }
}
if ($login == 1)
{
    @args = ('--login', @args);
}
exec('mate-terminal',@args);`
 
 put it to /usr/bin
 Call file x-terminal-emulator
 Change last line from mate-terminal to your terminal
 And dont forget 
 sudo update-alternatives --config x-terminal-emulator

**Comment by volnes** [comment]
or u can dig into advanced.py and indicator.py and change all lines where
`x-terminal-emulator -e `
To your terminal app like `konsole -e`
