### ISSUE TITLE
GP66 10UE i7 (10th Gen) , Linux Mint 20.2

### ISSUE THREAD

**Issue by DanielBaron86** [YoCodingMonster/OpenFreezeCenter#79]
Temp's not showing up in Advanced
![image](https://user-images.githubusercontent.com/25326906/144322370-e26b312b-521f-427d-8f01-b6e3c8f939b2.png)

On Auto fan speed not working
![image](https://user-images.githubusercontent.com/25326906/144322464-170f5d2a-4b0e-48e9-8039-12213f3caed2.png)

On Basic fans are not working on anything below fast

**Comment by DanielBaron86** [comment]
apt install python3-pip - y

this fails with
**E: Unable to locate package y**

**Comment by volnes** [comment]
There an error in install_deps.sh.
fix it by this
`apt install python3-pip -y`
