### ISSUE TITLE
app wont launch on executing startup script

### ISSUE THREAD

**Issue by Whitesaltyduck** [YoCodingMonster/OpenFreezeCenter#89]
I have a MSI GF63 10UC laptop with intel core i5-10500H and nvidia RTX 3050 laptop GPU. I have done a clean install of pop OS and when trying to launch the app by running the ./at_startup.sh script nothing happens. it does ask me for root password twice and i can see that it has created a conf.txt file but i cant see the GUI. 

the conf.txt file has the following text in it:
`1
0
140,0,20,40,45,50,60,70,0,20,40,45,50,60,70,
100
0,0,0,0,0,0,0,0,0,0,0,0,0,0,
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0`

i was looking through the other issues for the project and someone suggested to use the previous version of the software. After using the previous version, it's working perfectly fine now.

**Comment by r18duarte** [comment]
i had this problem too, but deleting the cfg and starting the program again fixed it
