### ISSUE TITLE
how to install on manjaaro arch

### ISSUE THREAD

**Issue by Vignes07** [YoCodingMonster/OpenFreezeCenter#92]

**Comment by IadRabbit** [comment]
sudo pacman -S tk xterm
cp /usr/bin/xterm /usr/bin/x-terminal-emulator
python indicator.py

**Comment by TheArcaneBrony** [comment]
ironically, that wont work, as the app is hardcoded to launch konsole....
either way uninstall manjaro, it has too many issues to be used unironically

**Comment by Vignes07** [comment]
Thank you for the information but it is working

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
