### ISSUE TITLE
MSI GF63 thin + Zorin OS 16

### ISSUE THREAD

**Issue by 3gis** [YoCodingMonster/OpenFreezeCenter#93]
I installed the 3.2 version and the functions that are working for me are: advanced option fans (the basic don't work), cooler boost, monitoring and EC mapping (haven't tried CPU options though). Battery threshold doesn't work sadly. Also, not sure why but the advanced option don't show temperature numbers when setting the speeds up (shows 0 on every option) but it still works.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
