### ISSUE TITLE
OpenFreezeCenter doesn't work on MSI Laptop GS75 Stealth 95F 

### ISSUE THREAD

**Issue by AM9327** [YoCodingMonster/OpenFreezeCenter#94]
Specs:
Laptop Version Brand: 2018 GS75 Stealth-248
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60 - 4.5GHz (Processor Count 6)
GPU: Nvidia Geforce RTX 2070 Max-Q
Display: 17.3" Fhd (1920x1080), 144Hz 
RAM: 32 GB (16G*2) DDR4 2666MHz 2
OS: LinuxMint 20.3 (una)

This program doesn't work at all with both non-root and root and I followed the steps correctly. Setting it up was no problem and running the command inside the folder works and displays the icon on your taskbar but if you go click on any of the buttons like change fan speed or open the monitor info nothing happens or opens besides if your not root it will ask you to enter your password but after that nothing happens.

Dragon Center obviously works just fine on my computer if I am using windows (11) with no issues.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
