### ISSUE TITLE
Multiple instances open themselves

### ISSUE THREAD

**Issue by matej-oliva** [YoCodingMonster/OpenFreezeCenter#95]
It is not something that happens a lot, but sometimes I look on taskbar and I see like 3 or 4 instances of OpenFreezeCenter. I close all of them but one and it still works.

Could you a check whether the app is already opened before the instance is started?

But anyways thanks for you great work!

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
