### ISSUE TITLE
GE66 Battery Threshold

### ISSUE THREAD

**Issue by gust4vsson** [YoCodingMonster/OpenFreezeCenter#96]
Hello!

The battery threshold doesnt seem to work for my GE66.
Is there a solution for this?

Thanks!

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
