### ISSUE TITLE
GS66 10ug-219+Manjaro Linux

### ISSUE THREAD

**Issue by kayoisdumb** [YoCodingMonster/OpenFreezeCenter#97]
Hi! I was wanting to know if someone could make a fork of this for Arch-based distros and support for the MSI GS66 10ug-219. Thanks!

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
