### ISSUE TITLE
Asking for sudo password all the time

### ISSUE THREAD

**Issue by mrvruj** [YoCodingMonster/OpenFreezeCenter#98]
Hello my Indian brother, I love your app. I am wondering if there is any way to stop the freeze center from asking for password every time a setting is changed? Thank you!

**Comment by Gameruption** [comment]
create a file in /etc/sudoers.d with the contents:
ALL ALL=(ALL:ALL) NOPASSWD: /usr/bin/python3,/usr/bin/nohup

you can also swap out the first ALL with your username and the second ALL with your device name to make it more secure

**Comment by TheArcaneBrony** [comment]
dont create such a file. you are opening your system up to enormous levels of danger. anyone running a command with `sudo nohup` would automatically have any random command elevated to root without any password prompts.

**Comment by YoCodingMonster** [comment]
Please see the new pre-release and in the tell if having issues in the discussion of that release tab only.

https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.2.1
